/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visigo;

import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.TreeMap;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;

/**
 *
 * @author Home
 */
public class Report2 extends javax.swing.JFrame {
    
    private Object[] tablePraticiens;
    private boolean isEditingNewRapport = false;

    /**
     * Creates new form Report
     */
    public Report2() {
        initComponents();
        proceed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(96, 149, 213));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RAPPORTS DE VISITE");

        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Visiteur :");

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Rapports :");

        jScrollPane1.setViewportView(jList1);

        jButton3.setText("Afficher le rapport");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(19, 19, 19))
        );

        jButton2.setText("Nouveau rapport");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Praticien");

        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("remplaçant");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jComboBox3.setToolTipText("");

        jLabel4.setText("Date visite");

        jTextField2.setText("JJ/MM/AA");

        jLabel5.setText("Motif visite");

        jLabel6.setText("Bilan");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Mettre à jour");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jCheckBox1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(22, 22, 22))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        this.refreshRapportsList();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.addInBase();
        jPanel2.setVisible(false);
        this.isEditingNewRapport = false;
        this.refreshRapportsList(); // to display created rapport in the list
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        this.synchroCheck();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        this.refreshComboBox3();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel2.setVisible(true);
        this.newRapport();
        this.isEditingNewRapport = true;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if(this.isCanSwitchDisplay() == true){
            this.isEditingNewRapport = false;
            String selectedRapportKey = ((ComboBoxItem)jList1.getSelectedValue()).getKey();
            this.displayRapport(Integer.valueOf(selectedRapportKey));
            jPanel2.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<ComboBoxItem> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<ComboBoxItem> jComboBox3;
    private javax.swing.JComboBox<ComboBoxItem> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<ComboBoxItem> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void proceed() {
        jPanel2.setVisible(false);
        populateComboBoxWithVisiteurs(); // CONSULTATION INIT
    }

    private void synchroCheck() {
        if (jCheckBox1.isSelected()) {
            jComboBox3.setEnabled(true);
        } else {
            jComboBox3.setEnabled(false);
            jComboBox3.setSelectedIndex(0);
        }
    }
    
    private void populateComboBoxWithPraticiens(JComboBox jComboBox, Object[] tablePraticiens){
        populateComboBoxWithPraticiens(jComboBox, tablePraticiens, 0);
    }
    
    private void populateComboBoxWithPraticiens(JComboBox jComboBox, Object[] tablePraticiens, int praNumToAvoid){
//        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(int i = 0; i < tablePraticiens.length; i++){
            boolean isOkToAdd = true;

            TreeMap < String, Object > treePraticien = (TreeMap < String, Object >)tablePraticiens[i];
            int pra_id = (int)treePraticien.get("PRA_NUM");
            String pra_nom = (String)treePraticien.get("PRA_NOM");
            String pra_prenom = (String)treePraticien.get("PRA_PRENOM");
            String pra_cp = (String)treePraticien.get("PRA_CP");
            
            if(praNumToAvoid != 0){
                if(praNumToAvoid == pra_id){
                    isOkToAdd = false;
                }
            }
            if(isOkToAdd){
//                model.addElement(new ComboBoxItem(pra_id, pra_nom + " " + pra_prenom + " (" + pra_cp + ")"));
                ComboBoxItem comboBoxItemToAdd = new ComboBoxItem(String.valueOf(pra_id), pra_nom + " " + pra_prenom + " (" + pra_cp + ")");
                jComboBox.addItem(comboBoxItemToAdd);
            }
        }
//        jComboBox.setModel(model);
    }
    
    private void refreshComboBox3(){
        jComboBox3.removeAllItems();
        jComboBox3.addItem(new ComboBoxItem("0", "NON CONNU"));
        if((ComboBoxItem)jComboBox1.getSelectedItem() != null){
            int selectedPraNum = Integer.parseInt(((ComboBoxItem)jComboBox1.getSelectedItem()).getKey());
            populateComboBoxWithPraticiens(jComboBox3, this.tablePraticiens, selectedPraNum);
        }
    }
    
    private void addInBase(){
        boolean isValid = true;
        
        int pra_num = Integer.parseInt(((ComboBoxItem)jComboBox1.getSelectedItem()).getKey());
        int rap_estremplace = 0;
        int pra_num_remplacant = 0;
        String rap_date = jTextField2.getText();
        String rap_motif = jComboBox2.getSelectedItem().toString();
        String rap_bilan = null;
        
        if(jCheckBox1.isSelected()){
            rap_estremplace = 1;
            pra_num_remplacant = Integer.parseInt(((ComboBoxItem)jComboBox3.getSelectedItem()).getKey());
        }
        //si bilan non vide
        if(!jTextArea2.getText().equals("")){
            rap_bilan = jTextArea2.getText();
        }
        
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        df.setLenient(false);
        java.util.Date date = null;
        
        try {
            date = df.parse(rap_date);
        } catch (ParseException e) {
            isValid = false;
            Tools.displayMessageTemporary(jLabel2, "Format de la date non valide - Usage : DD/MM/AAAA");
        }
        java.sql.Date date_sql = new java.sql.Date(date.getTime());
        
        //si praticien non choisi
        if(pra_num == 0){
            isValid = false;
        }
        //si motif vide
        if(rap_motif.equals("")){
            isValid = false;
        }
        //si date vide
        if(rap_date.equals("")){
            isValid = false;
        }
        
        if(isValid){
            
            TreeMap < Integer, Object > requestValues = new TreeMap <> ( );
            requestValues.put(1, ConnectionManager.getUserMatricule());
            requestValues.put(2, pra_num);
            requestValues.put(3, rap_estremplace);
            if(pra_num_remplacant == 0){
                requestValues.put(4, null);
            }else{
                requestValues.put(4, pra_num_remplacant);
            }
            requestValues.put(5, date_sql);
            requestValues.put(6, rap_bilan);
            requestValues.put(7, rap_motif);

            String req = "INSERT INTO rapport_visite (VIS_MATRICULE, PRA_NUM, RAP_ESTREMPLACE, PRA_NUM_REMPLACANT, RAP_DATE, RAP_BILAN, RAP_MOTIF) VALUES(?, ?, ?, ?, ?, ?, ?)";
            ConnectionManager.requestWrite(req, requestValues);
            
            Tools.displayMessageTemporary(jLabel2, "Enregistrement effectué");
        }else{
            Tools.displayMessageTemporary(jLabel2, "Un champ requis n'a pas été rempli");
        }
    }
    
    private void populateComboBoxWithVisiteurs(){
        String req2 = "SELECT VIS_MATRICULE, VIS_NOM, VIS_PRENOM FROM visiteur ORDER BY VIS_NOM;";
        Object[] tableVisiteurs = ConnectionManager.requestRead(req2);
        jComboBox4.addItem(new ComboBoxItem("0", "SELECTIONNEZ"));
        
//        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(int i = 0; i < tableVisiteurs.length; i++){

            TreeMap < String, Object > treePraticien = (TreeMap < String, Object >)tableVisiteurs[i];
            String pra_id = (String)treePraticien.get("VIS_MATRICULE");
            String pra_nom = (String)treePraticien.get("VIS_NOM");
            String pra_prenom = (String)treePraticien.get("VIS_PRENOM");
            
//            model.addElement(new ComboBoxItem(pra_id, pra_nom + " " + pra_prenom + " (" + pra_cp + ")"));
            jComboBox4.addItem(new ComboBoxItem(pra_id, pra_nom + " " + pra_prenom ));
            
        }
//        jComboBox4.setModel(model);
    }
    
    private void refreshRapportsList(){
        String selectedVisiteurMatricule = ((ComboBoxItem)jComboBox4.getSelectedItem()).getKey();
        if(selectedVisiteurMatricule != "0"){
            String req3 = "SELECT RAP_NUM, RAP_DATE FROM rapport_visite WHERE VIS_MATRICULE = \""+selectedVisiteurMatricule+"\";";
            Object[] tableRapports = ConnectionManager.requestRead(req3);

            DefaultListModel<ComboBoxItem> l1 = new DefaultListModel<>();
            for(int i = 0; i < tableRapports.length; i++){
                TreeMap < String, Object > treeRapport = (TreeMap < String, Object >)tableRapports[i];
                String rap_num = String.valueOf(treeRapport.get("RAP_NUM"));
                String rap_date = String.valueOf(treeRapport.get("RAP_DATE"));

                l1.addElement(new ComboBoxItem(rap_num, rap_num+" | "+rap_date));
            }
            jList1.setModel(l1);
        }
    }
    
    private void newRapport(){
        this.reinitFormRapport();
        
        java.util.Date currentDate = new java.util.Date();
        DateFormat df3 = new SimpleDateFormat("dd/MM/yyyy");
        jTextField2.setText(df3.format(currentDate));
        
        jButton1.setVisible(true);
        synchroCheck();
    }
    
    private void reinitFormRapport(){
        
        String req = "SELECT PRA_NUM, PRA_NOM, PRA_PRENOM, PRA_CP FROM praticien ORDER BY PRA_NOM;";
        Object[] tablePraticiens = ConnectionManager.requestRead(req);
        this.tablePraticiens = tablePraticiens;
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem(new ComboBoxItem("0", "SELECT"));
        populateComboBoxWithPraticiens(jComboBox1, tablePraticiens);
        
        jCheckBox1.setSelected(false);
        
        jComboBox3.removeAllItems();
        jComboBox3.addItem(new ComboBoxItem("0", "SELECTIONNEZ"));
        populateComboBoxWithPraticiens(jComboBox3, tablePraticiens);
        
        jTextField2.setText("");

        jComboBox2.removeAllItems();
        jComboBox2.addItem("Périodicité");
        jComboBox2.addItem("Nouveautés");
        jComboBox2.addItem("Chute de prescription");
        jComboBox2.addItem("Demande du praticien");
        jComboBox2.setEditable(true);
        
        jTextArea2.setText("");
        
        setRapportNormal();
    }
    
    private void displayRapport(int rapportNum){
        this.reinitFormRapport();
        
        String req = "SELECT * FROM rapport_visite WHERE RAP_NUM = \""+ rapportNum +"\";";
        Object[] tableRapports = ConnectionManager.requestRead(req);
        
        TreeMap < String, Object > treeRapport = (TreeMap < String, Object >)tableRapports[0];
        int rap_num = (int)treeRapport.get("RAP_NUM");
        String vis_matricule = (String)treeRapport.get("VIS_MATRICULE");
        int pra_num = (int)treeRapport.get("PRA_NUM");
        int rap_estRemplace = (int)treeRapport.get("RAP_ESTREMPLACE");
        int rap_numRemplacant = (int)treeRapport.get("PRA_NUM_REMPLACANT");
        String rap_date = treeRapport.get("RAP_DATE").toString();
        String rap_motif = (String)treeRapport.get("RAP_MOTIF");
        String rap_bilan = (String)treeRapport.get("RAP_BILAN");
        
        Tools.setSelectedValue(jComboBox1, pra_num);
        if(rap_estRemplace == 0){
            jCheckBox1.setSelected(false);
        }else{
            jCheckBox1.setSelected(true);
        }
        Tools.setSelectedValue(jComboBox3, rap_numRemplacant);
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat df2 = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date date = null;
        try {
            date = df.parse(rap_date);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        String date2 = df2.format(date);
        jTextField2.setText(date2);
                
        boolean isStandardSelectedMotif = false;
        for (int i = 0; i < jComboBox2.getItemCount(); i++){
            String item = jComboBox2.getItemAt(i);
            if (item.equals(rap_motif)){
                jComboBox2.setSelectedIndex(i);
                isStandardSelectedMotif = true;
                break;
            }
        }
        if(isStandardSelectedMotif == false){
            jComboBox2.addItem(rap_motif);
            jComboBox2.setSelectedItem(rap_motif);
        }
        
        jTextArea2.setText(rap_bilan);
        
        if(!vis_matricule.equals((String)ConnectionManager.getUserMatricule())){
            setRapportReadOnly();
        }else{
            jButton4.setVisible(true);
            synchroCheck();
        }
    }
    
    public void setRapportNormal(){
        Tools.setComboBoxNormal(jComboBox1);
        jCheckBox1.setEnabled(true);
        Tools.setComboBoxNormal(jComboBox3);
        jTextField2.setDisabledTextColor(new Color(184, 207, 229));
        jTextField2.setEnabled(true);
        Tools.setComboBoxNormal(jComboBox2);
        jTextArea2.setEditable(true);
        jButton1.setVisible(false);
        jButton4.setVisible(false);
    }
    
    public void setRapportReadOnly(){
        Tools.setComboBoxReadOnly(jComboBox1);
        jCheckBox1.setEnabled(false);
        Tools.setComboBoxReadOnly(jComboBox3);
        jTextField2.setDisabledTextColor(new Color(51,51,51));
        jTextField2.setEnabled(false);
        Tools.setComboBoxReadOnly(jComboBox2);
        jComboBox2.setEditable(true); //set again - wanted as editable by default
        jTextArea2.setEditable(false);
        jButton1.setVisible(false);
        jButton4.setVisible(false);
    }
    
    public boolean isCanSwitchDisplay(){
        boolean isCanSwitch = false;
        
        if(!jList1.isSelectionEmpty()){
            if(this.isEditingNewRapport){
                int confirmInput = JOptionPane.showConfirmDialog(this, 
                        "Voulez-vous fermer le rapport en cours de création?", "title", OK_CANCEL_OPTION);
                if(confirmInput == JOptionPane.YES_OPTION){
                    isCanSwitch = true;
                }
            }else{
                isCanSwitch = true;
            }
        }
        return isCanSwitch;
    }

}
